services:
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - blogspot-network
    depends_on:
      - user_service
      - post_service
      - comment_service
      - trending_service
    restart: unless-stopped

  user_db:
    image: postgres:16-alpine
    container_name: user_db
    environment:
      POSTGRES_USER: blogspotuser-table
      POSTGRES_PASSWORD: blogspotuserpass
      POSTGRES_DB: blogspotuser
    volumes: 
      - user_data:/var/lib/postgresql/data
      - ./user_service/users.sql:/docker-entrypoint-initdb.d/users.sql
    networks:
      - blogspot-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "blogspotuser-table", "-d", "blogspotuser"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://blogspotuser-table:blogspotuserpass@user_db:5432/blogspotuser
    depends_on:
      user_db:
        condition: service_healthy
    networks:
      - blogspot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  post_db:
    image: postgres:16-alpine
    container_name: post_db
    environment:
      POSTGRES_USER: blogspotpost-table
      POSTGRES_PASSWORD: blogspotpostpass
      POSTGRES_DB: blogspotpost
    volumes: 
      - post_data:/var/lib/postgresql/data
      - ./post_service/posts.sql:/docker-entrypoint-initdb.d/posts.sql
    networks:
      - blogspot-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "blogspotpost-table", "-d", "blogspotpost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped


  post_service:
    build:
      context: ./post_service
      dockerfile: Dockerfile
    container_name: post_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://blogspotpost-table:blogspotpostpass@post_db:5432/blogspotpost
      - USER_SERVICE_BASE=http://user_service:8000
      - COMMENT_SERVICE_BASE=http://comment_service:8002
    depends_on:
      post_db:
        condition: service_healthy
      user_service:
        condition: service_healthy
    networks:
      - blogspot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  comments_db:
    image: postgres:16-alpine
    container_name: comments_db
    environment:
      POSTGRES_USER: blogspotuser-table
      POSTGRES_PASSWORD: blogspotuserpass
      POSTGRES_DB: blogspotcomments
    volumes: 
      - comments_data:/var/lib/postgresql/data
      - ./comment_service/comments.sql:/docker-entrypoint-initdb.d/comments.sql
    networks:
      - blogspot-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "blogspotuser-table", "-d", "blogspotcomments"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped


  comment_service:
    build:
      context: ./comment_service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://blogspotuser-table:blogspotuserpass@comments_db:5432/blogspotcomments
      - USER_SERVICE_BASE=http://user_service:8000
    depends_on:
      comments_db:
        condition: service_healthy
      user_service:
        condition: service_healthy
    networks:
      - blogspot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  trending_service:
    build:
      context: ./trending_service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      - COMMENTS_DATABASE_URL=postgresql://blogspotuser-table:blogspotuserpass@comments_db:5432/blogspotcomments
      - POST_DATABASE_URL=postgresql://blogspotuser-table:blogspotuserpass@post_db:5432/blogspotpost
      - USER_DATABASE_URL=postgresql://blogspotuser-table:blogspotuserpass@user_db:5432/blogspotuser
      - USER_SERVICE_BASE=http://user_service:8000
      - POST_SERVICE_BASE=http://post_service:8001
      - COMMENT_SERVICE_BASE=http://comment_service:8002
    depends_on:
      user_service:
        condition: service_healthy
      post_service:
        condition: service_healthy
      comment_service:
        condition: service_healthy
    networks:
      - blogspot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  user_data:
  post_data:
  comments_data:

networks:
  blogspot-network:
    driver: bridge